### ISSUE TITLE
GaugeTool not downloading

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/glyphs-packages#10]
Have I done something wrong: 

```
22/06/2016 9:49:15.018 AM Glyphs[5100]: Git Clone output: Cloning into '~/Library/Application Support/Glyphs/Repositories/GuageTool'...
fatal: repository 'https://github.com/weiweihuanghuang/GaugeTool/tree/master/' not found
```

The link https://github.com/weiweihuanghuang/GaugeTool/tree/master/ exists?

**Comment by weiweihuanghuang** [comment]
Never mind! I linked the wrong thing https://github.com/schriftgestalt/glyphs-packages/pull/11

**Comment by weiweihuanghuang** [comment]
Ok it's still not installing via plugin manager??

**Comment by schriftgestalt** [comment]
there was a typo in the plugin name
