### ISSUE TITLE
Issue to add Grader

### ISSUE THREAD

**Issue by etunni** [schriftgestalt/glyphs-packages#136]
I can't add Grader from plugin manager,

![Screen Shot 2023-07-23 at 10 46 49](https://github.com/schriftgestalt/glyphs-packages/assets/5973399/4914b6f6-be11-47ae-a649-af90aed3230e)

**Comment by florianpircher** [comment]
Thanks for reporting the issue, it should be fixed now.

**Comment by etunni** [comment]
Yes!!

Have a nice day,
Eduardo Tunni
