### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/glyphs-packages#14]
It seem to have troubles with the plugin(s) updating automatically on a Glyphs restart. Particularly with the Kernkraft plugin. In the info.plist I changed the `CFBundleVersion` from `1.8` to `1.9.1`, kept the `CFBundleShortVersionString` at `1`. This didn’t help though. Is there something I am missing? The Github repo is always the newest version.

I guess changing `CFBundleShortVersionString` to `2` or so might be the solution?

**Comment by schriftgestalt** [comment]
The update does not depend on the version number any more. If installed from the plugin manager, it should just update the repositories automatically. I’ll have a look.

**Comment by Mark2Mark** [comment]
Good to know. If there is anything I can help you with, please let me know. For the moment we are removing the affected folder from the `Repositories` folder manually and reinstall from the PM.

**Comment by schriftgestalt** [comment]
You should be able to click the remove button and in then reinstall from the Plugin Manager

**Comment by Mark2Mark** [comment]
We are able to do so, but in some cases it doesn’t get the updated version into the Repo folder (after Glyphs restart).

**Comment by Mark2Mark** [comment]
I still encounter this problem. This time especially with the Skedge plugin. Every time I push an updated version, the updates don’t show in glyphs. Only if I uninstall and reinstall it in the Plugin Manager.

**Comment by schriftgestalt** [comment]
I seems that the update is only run when you open the Plugin Manager. I have al look.

edit: the update runs now ever time the app starts.

**Comment by Mark2Mark** [comment]
Awesome. Thank you so much!

**Comment by Mark2Mark** [comment]
Hello again,

It is still not working with Glyphs build 1101. In this case I checked if the update of my yesterday updated Skedge plugin comes through, but it doesn’t. A Glyphs restart (even an update of Glyphsapp) as well as opening the Plugin Manager doesn’t do anything.

When developing plugins and checking if the update works in Glyphs, I usually do this:
+ Uninstall from the Plugin Manager
+ Go to the Repositories folder and delete the Plugin Folder (repo)
+ Restart Glyphs, reinstall the plugin in the Plugin Manager
+ Restart Glyphs, check the plugin.

Quite tedious :D

**Comment by schriftgestalt** [comment]
I’m just messing aground with the plugins from the Plugin Manager and every time I run the Manager, all my manual changes are overwritten. So I wonder why it doesn’t work for you. 

It should be enough to just open the Manager and restart the app.

**Comment by Mark2Mark** [comment]
> just open the Manager and restart the app.
Hmm, I haven’t tried those two in combination. Will try once I got a new update for any of my plugins. Thanks for the quick reply!
