### ISSUE TITLE
systematise the use of Italic and Monospace for the menu items notation

### ISSUE THREAD

**Issue by schriftgestalt** [schriftgestalt/glyphs-packages#39]
Some entries use italic for (like `Filter > Beowulferize`) and some monospace (`View > Show Blindfold`).

**Comment by mekkablue** [comment]
I think I did it:
* _emphasis_ for UI text (like menu items)
* `code` for user input (like Python commands)
* no style change for keyboard shortcut, capitalised key names and dashes, e.g. Shift-Cmd-B

**Comment by schriftgestalt** [comment]
Thanks
