### ISSUE TITLE
Tabs for different kind of plugins

### ISSUE THREAD

**Issue by guidoferreyra** [schriftgestalt/glyphs-packages#4]
This is not really an issue but I think it could be great if besides the "All" and "Installed" tabs where a tab for every kind of plugin (Reporter, Filter, Palette, etc).

What do you think? Is this actually possible?

Best regards and nice addition to the app!

**Comment by schriftgestalt** [comment]
I was thinking about that already. Wanted to get it out first.

**Comment by guidoferreyra** [comment]
Great 👍

**Comment by schriftgestalt** [comment]
One thing tha just came to my mind is if the plugin type makes actually the best categories.

**Comment by guidoferreyra** [comment]
Yes is true. Besides the categories something like tags could be useful but I don´t know the possibilities of Alcatras.

**Comment by schriftgestalt** [comment]
Tags are not implemented in alkatraz but it can be easily added. At least if the number of tags is fixed.

**Comment by guidoferreyra** [comment]
Off topic but the Plugin Manager is crashing glyphs when I try to open it.

**Comment by schriftgestalt** [comment]
I fixed it.
