### ISSUE TITLE
List of plugins to consider

### ISSUE THREAD

**Issue by davelab6** [schriftgestalt/glyphs-packages#6]
Recently (April 21) I made this list of Glyphs plugins/scripts which you might find helpful:

https://remix-tools.com/

https://github.com/justanotherfoundry/freemix-glyphsapp

https://www.yanone.de/software/speedpunk/

https://github.com/yanone/ynlib

https://github.com/charlesmchen/typefacet https://github.com/homerjam/kerning-test

https://github.com/mekkablue

https://github.com/schriftgestalt

https://github.com/simoncozens

https://github.com/jenskutilek

https://github.com/Mark2Mark

https://github.com/impallari/Unitizer

https://github.com/ohbendy/Python-scripts-for-Glyphs

https://github.com/zar-nicolas20/GlyphsApp-nsilva-scripts

https://github.com/weiweihuanghuang/wei-glyphs-scripts

https://github.com/dadastudio/glyphsapp

https://github.com/m4rc1e/mf-glyphs-scripts

https://github.com/huertatipografica/huertatipografica-scripts

https://github.com/juandelperal/glyphsScripts

https://github.com/PDXIII/Glyphs-Scripts

https://github.com/c330s/glyphs-script--coursive-calt

https://github.com/quitequinn/WidthStudio

https://github.com/cenkdominic/glyphsapp-save-and-export

https://github.com/rp118758/Glyphs-scripts

https://github.com/guidoferreyra/Glyphs-Scripts

https://github.com/dyyybek/Glyphs-Scripts

https://github.com/BelaFrank/StringSmash

https://github.com/CatharsisFonts/Cormorant/tree/master/4.%20Glyphs%20Source%20Files/Cormorant%20Glyphs%20Scripts

https://github.com/Nevu/Show-Global-Glyph

https://github.com/Ckearns1210/CampaignBubbleViz

https://github.com/MrBrezina/python-workshop

https://github.com/ricardovv/2015_tipopython

**Comment by jenskutilek** [comment]
See also https://github.com/er1chu/awesome-glyphs
